name: Approve PR With Comment

on:
  issue_comment:
    types: [created]

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/approve"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: approvecomm

      - name: Approve Pull Request
        if: steps.approvecomm.outputs.BOOL_TRIGGERED == 'true'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.prcomm.outputs.PULL_REQUEST_NUMBER }}

      - name: listen for PR lgtm Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/lgtm"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: lgtmcomm

      - name: Approve Pull Request
        if: steps.lgtmcom.outputs.BOOL_TRIGGERED == 'true'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.lgtmcom.outputs.PULL_REQUEST_NUMBER }}

      #- name: print variables
      #  if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      #  run: echo "${USERNAME} made a triggering comment on PR# ${PR_NUMBER} for ${BRANCH_NAME}"
      #  env:
      #    BRANCH_NAME: ${{ steps.prcomm.outputs.BRANCH_NAME }}
      #    PR_NUMBER: ${{ steps.prcomm.outputs.PULL_REQUEST_NUMBER }}
      #    USERNAME: ${{ steps.prcomm.outputs.COMMENTER_USERNAME }}
