name: watcher

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
    
jobs:
  deploy:
    name: Watcher Job
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v1
        if: steps.check.outputs.triggered == 'true'
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${GITHUB_REF##*/}
      - name: Approve Pull Request
        if: steps.check.outputs.triggered == 'true'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}
